version: '3.7'

services:

  sample:
    container_name: projet_tele
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      
      
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: aclab2020
      MYSQL_USER: aclab2020
      MYSQL_PASSWORD: aclab2020
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql